# Generated by Django 3.2.14 on 2022-07-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('occupant', models.CharField(max_length=100)),
            ],
        ),
    ]
