# Generated by Django 3.2.14 on 2022-07-19 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kodjalink', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='KodjaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kodjalink.user')),
            ],
        ),
        migrations.AddField(
            model_name='link',
            name='kodjalink',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='kodjalink.kodjalink'),
        ),
    ]
