# Generated by Django 3.2.14 on 2022-07-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodjalink', '0002_auto_20220719_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='kodjalink',
            name='links',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
