# Generated by Django 3.2.14 on 2022-07-19 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kodjalink', '0003_kodjalink_links'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Link',
        ),
    ]
