# Generated by Django 4.0.6 on 2022-07-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linklist',
            name='links',
            field=models.ManyToManyField(blank=True, to='api.link'),
        ),
    ]
