# Generated by Django 4.0.6 on 2022-07-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_linklist_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='linklist',
            name='private',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
