# Generated by Django 4.0.6 on 2022-07-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_linklist_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linklist',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
