# Generated by Django 4.0.6 on 2022-07-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_linklist_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='thumbnail',
            field=models.URLField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='linklist',
            name='links',
            field=models.ManyToManyField(blank=True, null=True, to='api.link'),
        ),
    ]
