# Generated by Django 4.0.6 on 2022-07-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_link_description_alter_link_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='url_parsed',
            field=models.TextField(default='wasd', editable=False, max_length=300),
            preserve_default=False,
        ),
    ]
