# Generated by Django 4.0.6 on 2022-07-28 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_link_url_parsed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='url_parsed',
        ),
    ]
