# Generated by Django 4.0.6 on 2022-07-29 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_linklist_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='linklist',
            name='links',
            field=models.ManyToManyField(to='api.link'),
        ),
    ]
