# Generated by Django 4.0.6 on 2022-08-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_link_url_alter_linklist_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='description',
            field=models.TextField(
                blank=True,
                max_length=200,
                null=True
            ),
        ),
        migrations.AlterField(
            model_name='link',
            name='thumbnail',
            field=models.URLField(
                blank=True,
                default='',
                max_length=100,
                null=True
            ),
        ),
    ]
