# Generated by Django 4.0.6 on 2022-08-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_link_description_alter_link_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='title',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
