# Generated by Django 4.0.6 on 2022-08-02 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_link_description_alter_link_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkListItem',
            fields=[
                ('id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )),
                ('timestamp',
                    models.DateTimeField(auto_now_add=True)),
                ('link',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='api.link'
                    )),
                ('linklist',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='api.linklist'
                    )),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
